import { Room, UserProfile } from '../types';

export const INITIAL_USER: UserProfile = {
  studentId: '23IT117',
  fullName: 'Từ Thị Thanh Hương',
  email: 'huongttt.23it@vku.udn.vn',
  faculty: 'Khoa Khoa học Máy tính',
  major: 'Chuyên ngành Công nghệ phần mềm (song ngữ Nhật - Việt) (Kỹ sư)',
  academicYear: 'Khóa 2022 - 2027',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
};

export const VKU_BUILDINGS = ['Tất cả', 'Khu A', 'Khu V', 'Khu K', 'Thư viện'] as const;

export const TIME_SLOTS = [
  '07:00 - 09:15 (Tiết 1-3)',
  '09:30 - 11:45 (Tiết 4-6)',
  '13:00 - 15:15 (Tiết 7-9)',
  '15:30 - 17:45 (Tiết 10-12)',
  '18:00 - 20:15 (Tối / Sinh hoạt CLB)',
];

export const VKU_ROOMS: Room[] = [
  {
    id: 'room-a202',
    name: 'Phòng Hội thảo Smart Meeting A202',
    building: 'Khu A',
    floor: 'Tầng 2',
    capacity: 45,
    type: 'Conference',
    equipment: ['Máy chiếu Laser 4K', 'Hệ thống âm thanh hội nghị', 'Bảng kính cường lực', 'Wi-Fi 6 Dedicated', 'Điều hòa 2 chiều'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    description: 'Không gian họp và hội thảo cao cấp tòa nhà Hành chính A, trang bị màn hình tương tác thông minh chuyên dùng bảo vệ đồ án tốt nghiệp và hội thảo khoa học sinh viên.',
    availableSlots: ['07:00 - 09:15 (Tiết 1-3)', '13:00 - 15:15 (Tiết 7-9)', '15:30 - 17:45 (Tiết 10-12)'],
  },
  {
    id: 'room-v204',
    name: 'Phòng Lab AI & Data Science V204',
    building: 'Khu V',
    floor: 'Tầng 2',
    capacity: 50,
    type: 'Lab',
    equipment: ['50 PC Intel Core i7 / RTX 4060', 'Màn hình máy chiếu kép', 'Mạng LAN 1Gbps', 'Điều hòa công suất lớn', 'Bảng trắng'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    description: 'Phòng thực hành trí tuệ nhân tạo chuyên sâu khoa Công nghệ Thông tin VKU, máy cấu hình cao sẵn sàng huấn luyện mô hình Deep Learning và lập trình Cross-Platform.',
    availableSlots: ['09:30 - 11:45 (Tiết 4-6)', '13:00 - 15:15 (Tiết 7-9)', '18:00 - 20:15 (Tối / Sinh hoạt CLB)'],
  },
  {
    id: 'room-k101',
    name: 'VKU Maker Space & Robotics K101',
    building: 'Khu K',
    floor: 'Tầng 1',
    capacity: 60,
    type: 'StudySpace',
    equipment: ['Máy in 3D công nghiệp', 'Bộ KIT vi điều khiển STM32/ESP32', 'Trạm hàn điện tử', 'Khu bàn thảo luận nhóm', 'Điều hòa'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    description: 'Không gian sáng tạo mở hỗ trợ sinh viên VKU nghiên cứu Robocon, thiết bị IoT và dự án khởi nghiệp công nghệ sinh viên.',
    availableSlots: ['07:00 - 09:15 (Tiết 1-3)', '09:30 - 11:45 (Tiết 4-6)', '15:30 - 17:45 (Tiết 10-12)'],
  },
  {
    id: 'room-lib201',
    name: 'Phòng Thảo luận Nhóm Library LIB-201',
    building: 'Thư viện',
    floor: 'Tầng 2',
    capacity: 15,
    type: 'StudySpace',
    equipment: ['Smart TV 65 inch', 'Bảng di động', 'Cổng sạc đa năng tại bàn', 'Cách âm chuẩn thư viện', 'Wi-Fi Eduroam'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    description: 'Phòng thảo luận riêng biệt tại Thư viện số VKU, lý tưởng cho các nhóm sinh viên ôn thi, làm bài tập lớn và thuyết trình thử nghiệm.',
    availableSlots: ['07:00 - 09:15 (Tiết 1-3)', '13:00 - 15:15 (Tiết 7-9)', '18:00 - 20:15 (Tối / Sinh hoạt CLB)'],
  },
  {
    id: 'room-a101',
    name: 'Hội trường Lớn Trọng thể A101',
    building: 'Khu A',
    floor: 'Tầng 1',
    capacity: 250,
    type: 'Conference',
    equipment: ['Màn hình LED P2 400 inch', 'Dàn âm thanh Line Array', 'Sân khấu biểu diễn', 'Hệ thống ánh sáng DMX', 'Phòng điều khiển kỹ thuật'],
    status: 'busy',
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    description: 'Hội trường trung tâm phục vụ các sự kiện quốc tế, lễ khai giảng, hội nghị sinh viên nghiên cứu khoa học cấp trường và TechTalk doanh nghiệp.',
    availableSlots: ['18:00 - 20:15 (Tối / Sinh hoạt CLB)'],
  },
  {
    id: 'room-v305',
    name: 'Phòng Lab Thiết kế Đồ họa & Game V305',
    building: 'Khu V',
    floor: 'Tầng 3',
    capacity: 40,
    type: 'Lab',
    equipment: ['40 iMac 27 inch 5K', 'Bảng vẽ kỹ thuật số Wacom', 'Máy chiếu Full HD', 'Wi-Fi 6', 'Điều hòa không khí'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    description: 'Phòng máy Mac tiêu chuẩn phục vụ môn học UI/UX Design, Thiết kế 3D và phát triển ứng dụng di động iOS/Android tại VKU.',
    availableSlots: ['07:00 - 09:15 (Tiết 1-3)', '09:30 - 11:45 (Tiết 4-6)', '13:00 - 15:15 (Tiết 7-9)'],
  },
  {
    id: 'room-k302',
    name: 'Phòng Seminar Vi mạch & Bán dẫn K302',
    building: 'Khu K',
    floor: 'Tầng 3',
    capacity: 35,
    type: 'Classroom',
    equipment: ['Bảng tương tác thông minh Maxhub', 'Hệ thống hội nghị truyền hình trực tuyến', 'Máy đo xung số Oscilloscope', 'Điều hòa'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    description: 'Phòng nghiên cứu và đào tạo chuyên sâu ngành Thiết kế Vi mạch Bán dẫn mới thành lập của VKU hợp tác với các tập đoàn công nghệ toàn cầu.',
    availableSlots: ['09:30 - 11:45 (Tiết 4-6)', '15:30 - 17:45 (Tiết 10-12)'],
  },
  {
    id: 'room-lib-silent',
    name: 'Khu Tự học Không gian Yên tĩnh LIB-G01',
    building: 'Thư viện',
    floor: 'Tầng Trệt',
    capacity: 80,
    type: 'StudySpace',
    equipment: ['Bàn học cá nhân có vách ngăn', 'Đèn LED chống mỏi mắt', 'Khu vực cắm điện laptop', 'Máy lọc không khí'],
    status: 'available',
    imageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    description: 'Khu vực tự học yên tĩnh tuyệt đối tại Thư viện số VKU, mở cửa phục vụ sinh viên mùa ôn thi và làm đồ án tốt nghiệp.',
    availableSlots: ['07:00 - 09:15 (Tiết 1-3)', '09:30 - 11:45 (Tiết 4-6)', '13:00 - 15:15 (Tiết 7-9)', '15:30 - 17:45 (Tiết 10-12)', '18:00 - 20:15 (Tối / Sinh hoạt CLB)'],
  },
];
